--
--  Curso Oracle 19c Administración
--
-- DROP TABLE TEMPO;

SET echo ON
CREATE TABLE TEMPO
  (col CHAR(1000)
  ) TABLESPACE tbs_02;
INSERT INTO TEMPO VALUES ('netec');
INSERT INTO TEMPO SELECT * FROM TEMPO;
INSERT INTO TEMPO SELECT * FROM TEMPO;
INSERT INTO TEMPO SELECT * FROM TEMPO;
INSERT INTO TEMPO SELECT * FROM TEMPO;
INSERT INTO TEMPO SELECT * FROM TEMPO;
INSERT INTO TEMPO SELECT * FROM TEMPO;
INSERT INTO TEMPO SELECT * FROM TEMPO;
INSERT INTO TEMPO SELECT * FROM TEMPO;
INSERT INTO TEMPO SELECT * FROM TEMPO;
INSERT INTO TEMPO SELECT * FROM TEMPO;
INSERT INTO TEMPO SELECT * FROM TEMPO;
INSERT INTO TEMPO SELECT * FROM TEMPO;
INSERT INTO TEMPO SELECT * FROM TEMPO;
INSERT INTO TEMPO SELECT * FROM TEMPO;
COMMIT;
quit

