--
-- Curso Oracle 19c
--

drop tablespace ts_mod12 including contents and datafiles;

create tablespace ts_mod12 datafile '/u02/oradata/orcl/df_mod12' size 500M extent management local segment space management auto;

drop table t_mod12;

create table t_mod12 (
 id number generated by default on null as identity,
 valor varchar2(100)
) tablespace ts_mod12;

insert into t_mod12(valor) values ('XXXXXXXXXXXXXXXXXXXX');

/
begin
	for i in 1..10 loop
		insert into t_mod12(valor) select valor from t_mod12;
	end loop;
	commit;
end;
/

select count(1) from t_mod12;

quit;
